version: '4'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data/mongodb:/data/db

  mysql_order:
    image: mysql:8.3.0
    container_name: mysql-order-container
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: order_service
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/order-init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/mysql_order:/var/lib/mysql

  mysql_inventory:
    image: mysql:8.3.0
    container_name: mysql-inventory-container
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: inventory_service
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql/init.d:/docker-entrypoint-initdb.d # !!important, map the folder instead of the any actual file
#      - ./docker/mysql/inventory-init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/mysql_inventory:/var/lib/mysql

  keycloak-mysql:
    container_name: keycloak-mysql-container
    image: mysql:8.3.0
    volumes:
      - ./volume-data/mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
  keycloak:
      container_name: keycloak
      image: quay.io/keycloak/keycloak:24.0.1
      command: [ "start-dev", "--import-realm" ]
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      ports:
        - "8181:8080"
      volumes:
        - ./docker/keycloak/realms/:/opt/keycloak/data/import/
      depends_on:
        - keycloak-mysql