version: '4'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - ./data/mongodb:/data/db
  mysql_order:
    image: mysql:8.3.0
    container_name: mysql-order-container
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: order_service
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/order-init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/mysql_order:/var/lib/mysql

  mysql_inventory:
    image: mysql:8.3.0
    container_name: mysql-inventory-container
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: inventory_service
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql/inventory-init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/mysql_inventory:/var/lib/mysql